# CloudSync - App Server
# Flask + MongoDB - on Gunicorn
# .travis.yml

# Basado en: https://medium.com/@javierfernandes/continuous-deployment-con-docker-travis-heroku-c24042fb830b

sudo: required
language: python
python:
  - 3.6
services:
  - docker
before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

install:
  # install requirements
  - pip install -U coverage coveralls PyYAML
  # create copy of source code to mirror docker-compose structure
  - sudo mkdir /home/ubuntu/
  - sudo find . -name "*.py" -exec rsync -qR {} /home/ubuntu \;
  # build dockerized environment to run tests
  - docker-compose build 
  - docker-compose up -d
script: 
  # unit tests w/coverage, in docker-compose env
  - docker exec -u root -it app-server-flask bash -c "coverage run --omit */virtualenv/* -m unittest tests/*.py -v"
  - coverage report
after_success:
  # submit results to coveralls, on success
  - coveralls
branches:
  # include ONLY these branches
  only:
    - qa
    - master
deploy:
  - provider: script
    script:
      # build docker images, push to dockerhub & heroku
      docker build -t juanmg0511/7599-trabajoprofesional-cloudsync-appserver:qa .;
      docker tag juanmg0511/7599-trabajoprofesional-cloudsync-appserver:qa registry.heroku.com/$HEROKU_APP_NAME_QA/web;
      docker push juanmg0511/7599-trabajoprofesional-cloudsync-appserver:qa;
      docker push registry.heroku.com/$HEROKU_APP_NAME_QA/web;
      heroku container:release web --app $HEROKU_APP_NAME_QA
    on:
      branch: qa

  - provider: script
    script:
      # build docker images, push to dockerhub & heroku
      docker build -t juanmg0511/7599-trabajoprofesional-cloudsync-appserver:production .;
      docker tag juanmg0511/7599-trabajoprofesional-cloudsync-appserver:production registry.heroku.com/$HEROKU_APP_NAME/web;
      docker push juanmg0511/7599-trabajoprofesional-cloudsync-appserver:production;
      docker push registry.heroku.com/$HEROKU_APP_NAME/web;
      heroku container:release web --app $HEROKU_APP_NAME
    on:
      branch: master
